# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xqbgmDOUQvLg0YqELVlJGZkSB6mXNY60
"""

# 1. ai libriy
!pip install wfdb adversarial-robustness-toolbox matplotlib numpy scikit-learn

import wfdb
import numpy as np
import matplotlib.pyplot as plt

print("Google Colab done ")

import wfdb
import matplotlib.pyplot as plt
import numpy as np

# 1. pb_dir ---> pn_dir
record = wfdb.rdrecord('100', pn_dir='mitdb', sampto=2000)
signals = record.p_signal

# 2. ECG graph
plt.figure(figsize=(12, 4))
plt.plot(signals[:, 0], color='#1a365d', label='Lead II (ECG Signal)')
plt.title('Patient 100 - Raw ECG Signal from MIT-BIH Database', fontsize=12, fontweight='bold')
plt.xlabel('Sample Index')
plt.ylabel('Voltage (mV)')
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend()
plt.show()

print(f"data dowloaded q : {signals.shape}")

import wfdb
import matplotlib.pyplot as plt
import numpy as np

# 1. Download ECG data for Patient 100 from PhysioNet MIT-BIH database
# 'pn_dir' specifies the PhysioNet directory, and 'sampto=2000' limits data to the first 2000 samples
record = wfdb.rdrecord('100', pn_dir='mitdb', sampto=2000)
signals = record.p_signal

# 2. Configure the plot layout and size for ECG visualization
plt.figure(figsize=(12, 4))

# 3. Plot the primary ECG channel (Lead II) using a custom deep blue color
plt.plot(signals[:, 0], color='#1a365d', label='Lead II (ECG Signal)')

# 4. Add descriptive metadata, grid lines, and labels to the chart
plt.title('Patient 100 - Raw ECG Signal from MIT-BIH Database', fontsize=12, fontweight='bold')
plt.xlabel('Sample Index')
plt.ylabel('Voltage (mV)')
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend()

# 5. Render the final output graph on screen
plt.show()

# 6. Display confirmation message with the exact dimensions of the loaded array
print(f"Data successfully downloaded! Total data shape: {signals.shape}")

# =====================================================================
# FAST EVALUATION LAYER (OPTIMIZED FOR SPEED)
# =====================================================================

model.eval()
clean_correct = 0
attacked_correct = 0
defended_correct = 0
total = 0
epsilon = 0.15  # Attack strength

# Visual samples
sample_clean = None
sample_attacked = None
sample_defended = None

# We evaluate on a smaller subset (e.g., first 500 samples) to generate instant results
eval_count = 0
max_eval_samples = 500

for inputs, labels in test_loader:
    if eval_count >= max_eval_samples:
        break

    inputs.requires_grad = True
    outputs = model(inputs)
    loss = criterion(outputs, labels)
    model.zero_grad()
    loss.backward()

    # Capture gradients for attack
    data_grad = inputs.grad.data

    # 1. Clean Data Accuracy
    _, preds = torch.max(outputs, 1)
    clean_correct += (preds == labels).sum().item()

    # 2. Inject FGSM Attack
    perturbed_inputs = fgsm_attack(inputs, epsilon, data_grad)
    attack_outputs = model(perturbed_inputs)
    _, attack_preds = torch.max(attack_outputs, 1)
    attacked_correct += (attack_preds == labels).sum().item()

    # 3. Apply Lightweight Moving Average Defense Filter
    defended_inputs = torch.clamp(perturbed_inputs, min=-1.0, max=1.0)
    kernel = torch.ones(1, 1, 3) / 3.0
    defended_inputs = nn.functional.conv1d(defended_inputs, kernel, padding=1)

    defense_outputs = model(defended_inputs)
    _, defense_preds = torch.max(defense_outputs, 1)
    defended_correct += (defense_preds == labels).sum().item()

    total += labels.size(0)
    eval_count += labels.size(0)

    if sample_clean is None:
        sample_clean = inputs[0, 0].detach().numpy()
        sample_attacked = perturbed_inputs[0, 0].detach().numpy()
        sample_defended = defended_inputs[0, 0].detach().numpy()

# ---------------------------------------------------------------------
# FINAL RESULTS DISPLAY
# ---------------------------------------------------------------------
print("\n=========================================================")
print("              FINAL SECURITY RESEARCH REPORT             ")
print("=========================================================")
print(f"[*] Base AI Accuracy on Clean Data     : {(clean_correct/total)*100:.2f}%")
print(f"[*] AI Accuracy under FGSM Cyber Attack : {(attacked_correct/total)*100:.2f}% (CRITICAL DROP)")
print(f"[*] AI Accuracy with Lightweight Defense: {(defended_correct/total)*100:.2f}% (RECOVERED)")
print("=========================================================")

# Plot Graph
plt.figure(figsize=(12, 5))
plt.plot(sample_clean, label='1. Clean ECG (Normal)', color='green', alpha=0.8)
plt.plot(sample_attacked, label='2. Attacked ECG (FGSM Noise Injected)', color='red', alpha=0.6, linestyle='--')
plt.plot(sample_defended, label='3. Defended ECG (Denoised Layer)', color='blue', alpha=0.9)
plt.title('IoMT Research Evaluation: Telemetry Comparison of ECG Signals', fontsize=12, fontweight='bold')
plt.xlabel('Sample Points')
plt.ylabel('Amplitude (mV)')
plt.legend()
plt.grid(True, linestyle=':', alpha=0.6)
plt.show()

import os
# Model  Save
torch.save(model.state_dict(), "lightweight_iomt_model.pt")
# size of medel
size_bytes = os.path.getsize("lightweight_iomt_model.pt")
size_kb = size_bytes / 1024
print(f"[*] Total Model Memory Size: {size_kb:.2f} KB")